// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{},"license":{"name":"MIT","url":"https://opensource.org/license/mit"},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/files":{"get":{"description":"Retrieve information about all existing files","produces":["application/json"],"tags":["files"],"summary":"Retrieve all files","responses":{"200":{"description":"Every existing file","schema":{"type":"array","items":{"$ref":"#/definitions/models.File"}}}}}}},"definitions":{"models.File":{"type":"object","properties":{"data":{"type":"array","items":{"type":"integer"}},"file_name":{"type":"string"},"has_access":{"description":"List of user IDs","type":"array","items":{"type":"string"}},"id":{"type":"string"},"tags":{"type":"array","items":{"type":"string"}},"user_id":{"type":"string"}}}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.2",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "File transfer API",
	Description:      "Webserver providing saving and retrieval of files from MongoDB",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
