basePath: /
definitions:
  models.File:
    properties:
      blob_url:
        type: string
      file_name:
        type: string
      has_access:
        description: List of user IDs
        items:
          type: string
        type: array
      id:
        type: string
      path:
        type: string
      tags:
        items:
          type: string
        type: array
      user_id:
        type: string
    type: object
  models.FileDownloadRequest:
    properties:
      path:
        type: string
      user_id:
        type: string
    type: object
  models.FileResponse:
    properties:
      path:
        type: string
      size:
        type: integer
      url:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
  description: Webserver providing saving and retrieval of files from MongoDB
  license:
    name: MIT
    url: https://opensource.org/license/mit
  title: File transfer API
  version: "0.2"
paths:
  /download:
    post:
      consumes:
      - application/json
      description: Download a file with path
      parameters:
      - description: File metadata
        in: body
        name: file
        required: true
        schema:
          $ref: '#/definitions/models.FileDownloadRequest'
      produces:
      - application/octet-stream
      responses:
        "200":
          description: File content
          schema:
            type: file
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Download a file
      tags:
      - files
  /file:
    post:
      consumes:
      - application/json
      description: Create a new file record in the database
      parameters:
      - description: File object to create
        in: body
        name: file
        required: true
        schema:
          $ref: '#/definitions/models.File'
      produces:
      - application/json
      responses:
        "201":
          description: Created file object
          schema:
            $ref: '#/definitions/models.File'
        "400":
          description: Invalid request payload
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new file
      tags:
      - files
  /file/{file_id}:
    delete:
      description: Remove a file from the database by its ID
      parameters:
      - description: File ID
        in: path
        name: file_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'Result: success'
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid file ID
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete a specific file
      tags:
      - files
    get:
      description: Get information about a file by its ID
      parameters:
      - description: File ID
        in: path
        name: file_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Retrieved file object
          schema:
            $ref: '#/definitions/models.File'
        "400":
          description: Invalid file ID
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Retrieve a specific file
      tags:
      - files
    put:
      consumes:
      - application/json
      description: Update the details of an existing file by its ID
      parameters:
      - description: File ID
        in: path
        name: file_id
        required: true
        type: string
      - description: File object with updated information
        in: body
        name: file
        required: true
        schema:
          $ref: '#/definitions/models.File'
      produces:
      - application/json
      responses:
        "200":
          description: Updated file object
          schema:
            $ref: '#/definitions/models.File'
        "400":
          description: Invalid request payload or file ID
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Update an existing file
      tags:
      - files
  /file/user/{user_id}:
    get:
      description: Retrieve information about all files uploaded by a specific user
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Files uploaded by the user
          schema:
            items:
              $ref: '#/definitions/models.File'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Retrieve files by user
      tags:
      - files
  /files:
    get:
      description: Retrieve information about all existing files
      produces:
      - application/json
      responses:
        "200":
          description: Every existing file
          schema:
            items:
              $ref: '#/definitions/models.File'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Retrieve all files
      tags:
      - files
  /upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload file with path and content
      parameters:
      - description: JSON metadata with path
        in: formData
        name: metadata
        required: true
        type: string
      - description: File content
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.FileResponse'
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Upload a file
      tags:
      - files
swagger: "2.0"
