# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - pipeline

pool:
  vmImage: "ubuntu-latest"

variables:
  SSH_HOST: "20.251.144.99"
  SSH_USER: "azureuser"
  REPO_URL: "https://github.com/maksnowak/FileSharingSystem"
  WORK_DIR: "/home/app"

stages:
  - stage: Deploy
    displayName: Deploy Application
    jobs:
      - job: SSH_and_Deploy
        displayName: SSH to VM and Deploy
        steps:
          - task: InstallSSHKey@0
            inputs:
              hostName: $(SSH_HOST)
              sshKeySecureFile: "pisVMkey.pem"

          - script: |
              ssh -o StrictHostKeyChecking=no $(SSH_USER)@$(SSH_HOST) << 'EOF'
                echo "SSH Connection Established"
                mkdir -p $(WORK_DIR)
                cd $(WORK_DIR)
                if [ -d ".git" ]; then
                  git pull
                else
                  git clone $(REPO_URL) .
                fi
                docker-compose up -d --build
              EOF
            displayName: SSH into VM and Deploy
