# https://aka.ms/yaml

trigger:
  - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: deploy-variables
  - group: docker-registry-credentials

stages:
  - stage: BuildAndTest
    jobs:
      - template: templates/go-test.yml
        parameters:
          appName: "file_transfer"
          directory: "file-transfer/"
      - template: templates/go-test.yml
        parameters:
          appName: "file_encryption"
          directory: "file-encryption/"
      - template: templates/go-test.yml
        parameters:
          appName: "accounts"
          directory: "accounts/"
      - template: templates/vue-test.yml
        parameters:
          appName: "frontend"
          directory: "frontend/"

  - stage: DockerBuildAndPush
    dependsOn: BuildAndTest
    condition: succeeded()
    jobs:
      - template: templates/docker-build-push.yml
        parameters:
          appName: "file_transfer"
          directory: "file-transfer/"
      - template: templates/docker-build-push.yml
        parameters:
          appName: "file_encryption"
          directory: "file-encryption/"
      - template: templates/docker-build-push.yml
        parameters:
          appName: "accounts"
          directory: "accounts/"

  - stage: Deploy
    dependsOn: DockerBuildAndPush
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - template: templates/deploy.yml
        parameters:
          appName: "file_transfer"
          port: "8080:8080"
      - template: templates/deploy.yml
        parameters:
          appName: "file_encryption"
          directory: "file-encryption/"
      - template: templates/deploy.yml
        parameters:
          appName: "accounts"
          directory: "accounts/"
