services:
  file-encryption:
    build: file-encryption
    container_name: file-encryption
    image: file-encryption:0.1
  file-transfer:
    build: file-transfer
    container_name: file-transfer
    image: file-transfer:0.1
  accounts:
    build: accounts
    container_name: accounts
    image: accounts:0.1
  frontend:
    build: frontend
    container_name: frontend
    image: frontend:0.1
    ports:
      - "80:80"
