services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  file-encryption:
    build: file-encryption
    container_name: file-encryption
    image: pis/file-encryption:0.2
    ports:
      - "7780:7780"
    environment:
      - APP_ENV=prod
    volumes:
      - ./file-encryption/.env:/app/config/.env
  file-transfer:
    depends_on:
      - mongodb
    build: file-transfer
    container_name: file-transfer
    image: pis/file-transfer:0.1
    ports:
      - "8080:8080"
    volumes:
      - ./file-transfer/.env:/app/config/.env
  accounts:
    build: accounts
    container_name: accounts
    image: pis/accounts:0.2
    ports:
      - "2024:2024"
    environment:
      - APP_ENV=prod
    volumes:
      - ./accounts/.env:/app/config/.env
  frontend:
    build: frontend
    container_name: frontend
    image: frontend:0.1
    ports:
      - "80:80"
    volumes:
      - ./frontend/.env:/app/config/.env
