services:
  file-encryption:
    build: file-encryption
    container_name: file-encryption
    image: file-encryption:0.1
    env_file: .env
  file-transfer:
    build: file-transfer
    container_name: file-transfer
    image: file-transfer:0.1
  accounts:
    build: accounts
    container_name: accounts
    image: accounts:0.2
    ports:
      - "2024:2024"
    environment:
      - APP_ENV=prod
  frontend:
    build: frontend
    container_name: frontend
    image: frontend:0.1
    ports:
      - "80:80"
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
