basePath: /
definitions:
  models.Credentials:
    properties:
      passwordHash:
        example: 29a52d8ceb75e13713b42509ca3f203372d0cc68bcd797f49538d1ee244d0270
        type: string
      username:
        example: NissanSkyline
        type: string
    type: object
  models.HTTP200:
    properties:
      message:
        example: Operation successful
        type: string
    type: object
  models.HTTP400:
    properties:
      <plain string>:
        example: Invalid request body
        type: string
    type: object
  models.HTTP404:
    properties:
      <plain string>:
        example: Could not find requested data
        type: string
    type: object
  models.HTTP500:
    properties:
      <plain string>:
        example: Error while processing request
        type: string
    type: object
  models.Register:
    properties:
      email:
        example: 1.9TDI@germany.gov
        type: string
      passwordHash:
        example: 2b2961a431b23c9007efe270c1d7eb79c19d4192d7cd2d924176eb0b19e7d2a1
        type: string
      passwordSalt:
        example: 720f6ac947ab8e448c3a7bb9109e62b72d79a388cb8e05469a6188d76b2e02b3
        type: string
      role:
        example: admin
        type: string
      username:
        example: VolkswagenPassatB5
        type: string
    type: object
  models.Salt:
    properties:
      passwordSalt:
        example: 8cf2283ad6ef0a3266059b418a73f8479338233ea2c4bcd3c1f51c39f13ae7dc
        type: string
      username:
        example: ToyotaCorolla
        type: string
    type: object
  models.Update:
    properties:
      email:
        example: 2.5V6TDI@germany.gov
        type: string
      ownedFiles:
        example:
        - 6740a84ebda333c3ff62b0fb
        - 18727a085b5ff06008027b11
        - bac300aba05c5d3610fcd03b
        items:
          type: string
        type: array
      passwordHash:
        example: 15c22c39b6d979a8da5b6185d70a7937630319288cc39fd74a3f705c397281a2
        type: string
      passwordSalt:
        example: 3246e8fa9472a7c958f3afd81a50acb042ddef9f1558ff3d0ccd4771309aca1f
        type: string
      sharedFiles:
        example:
        - ef4dc590d2d1356ca4137598
        items:
          type: string
        type: array
    type: object
  models.User:
    properties:
      createdAt:
        example: "2024-12-11T13:58:47.977Z"
        type: string
      email:
        example: suzuki.swift@my.beloved
        type: string
      id:
        example: 675f9a97ca1d148373316ae4
        type: string
      ownedFiles:
        example:
        - 6740a84ebda333c3ff62b0fb
        - 18727a085b5ff06008027b11
        items:
          type: string
        type: array
      passwordHash:
        example: f1881511920da79a65164eec5f99b18fd45a4e117b9bcedebe01364899c48d54
        type: string
      passwordSalt:
        example: 8aa02738f5b472d7c0c4293473ff968cdddd14718be579d8f4ebd792e0f81ef7
        type: string
      role:
        example: admin
        type: string
      sharedFiles:
        example:
        - ef4dc590d2d1356ca4137598
        - cef1ee14b343dbae4d77020c
        items:
          type: string
        type: array
      username:
        example: SuzukiSwift
        type: string
    type: object
info:
  contact: {}
  description: Webserver serving a complete implementation of account managing API
    endpoint.
  license:
    name: MIT
    url: https://opensource.org/license/mit
  title: Accounts API
  version: "0.1"
paths:
  /accounts/:
    get:
      description: Retrieve information about all existing accounts
      produces:
      - application/json
      responses:
        "200":
          description: Every existing account
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Server could not retrieve or process the data
          schema:
            $ref: '#/definitions/models.HTTP500'
      summary: Retrieve all account data
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Create a User record in the database
      parameters:
      - description: Necessary account details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Register'
      produces:
      - application/json
      responses:
        "200":
          description: Account created successfully
          schema:
            $ref: '#/definitions/models.HTTP200'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/models.HTTP400'
        "500":
          description: Server could not save the account
          schema:
            $ref: '#/definitions/models.HTTP500'
      summary: Create an account
      tags:
      - accounts
  /accounts/{user_id}:
    delete:
      description: Delete an account with given ID
      parameters:
      - description: ID of the user to delete
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Account deleted successfully
          schema:
            $ref: '#/definitions/models.HTTP200'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/models.HTTP400'
        "404":
          description: No user with given ID was found
          schema:
            $ref: '#/definitions/models.HTTP404'
        "500":
          description: Server could not delete the account
          schema:
            $ref: '#/definitions/models.HTTP500'
      summary: Delete an account
      tags:
      - accounts
    get:
      description: Retrieve information about an account with given ID
      parameters:
      - description: ID of the user to retrieve
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Account retrieved successfully
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Invalid ID format
          schema:
            $ref: '#/definitions/models.HTTP400'
        "404":
          description: No user with given ID was found
          schema:
            $ref: '#/definitions/models.HTTP404'
      summary: Retrieve an account
      tags:
      - accounts
    put:
      consumes:
      - application/json
      description: Update an account with given ID
      parameters:
      - description: ID of the user to update
        in: path
        name: user_id
        required: true
        type: string
      - description: Data to be updated (no need for all the fields)
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Update'
      produces:
      - application/json
      responses:
        "200":
          description: Account updated successfully
          schema:
            $ref: '#/definitions/models.HTTP200'
        "400":
          description: Invalid ID format or request body
          schema:
            $ref: '#/definitions/models.HTTP400'
        "404":
          description: No user with given ID was found
          schema:
            $ref: '#/definitions/models.HTTP404'
        "500":
          description: Server could not update the account
          schema:
            $ref: '#/definitions/models.HTTP500'
      summary: Update an account
      tags:
      - accounts
  /login/:
    post:
      consumes:
      - application/json
      description: Verify users password and return the User if it is correct (login
        successful)
      parameters:
      - description: Users login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: User credentials valid (login successful)
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Invalid request body or password
          schema:
            $ref: '#/definitions/models.HTTP400'
        "404":
          description: No account with given username was found
          schema:
            $ref: '#/definitions/models.HTTP404'
      summary: Verify users password
      tags:
      - login
  /login/{username}:
    get:
      description: Get the password salt of the user with given username
      parameters:
      - description: Username of the account to retrieve the password salt for
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Password salt retrieved successfully
          schema:
            $ref: '#/definitions/models.Salt'
        "404":
          description: No account with given username was found
          schema:
            $ref: '#/definitions/models.HTTP404'
      summary: Get the user's password salt
      tags:
      - login
swagger: "2.0"
