parameters:
  appName: ""
  directory: ""

jobs:
  - job: Docker_${{ parameters.appName }}
    displayName: "Docker operations for ${{ parameters.appName }}"
    steps:
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: $(dockerRegistry)
      - task: Docker@2
        displayName: Build and Push
        inputs:
          command: buildAndPush
          Dockerfile: $(Build.SourcesDirectory)/${{ parameters.directory }}/Dockerfile
          repository: $(dockerRegistry)/${{ parameters.appName }}
          tags: |
            $(Build.BuildId)
        env:
          dockerRegistry: $(dockerRegistry)
