parameters:
  appName: ""
  directory: ""

jobs:
  - job: Test_${{ parameters.appName }}
    displayName: "Test ${{ parameters.appName }}"
    steps:
      - script: |
          cd ${{ parameters.directory }}
          go build -o ${{ parameters.appName }}
          go test ./...
        displayName: "Build and test ${{ parameters.appName }}"
